name: unit_tests

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install package
      run: python setup.py install
    - name: Run tests
      run: pytest -v tests
